### ISSUE TITLE
Outdated version of shfmt

### ISSUE THREAD

**Issue by jooola** [MaxWinterstein/shfmt-py#9]
Hi,
The latest version of shfmt is not yet distributed.

Could it be possible to automate the upgrade process ?

What about creating an organization (shfmt-py/shfmt-py) to make the package a bit more "official", and I could help you maintain it.

**Comment by dudicoco** [comment]
@MaxWinterstein any plans on keeping this repo maintained or is it recommended to fork it instead?

**Comment by MaxWinterstein** [comment]
@dudicoco I will take care of this, sorry for the delay.

**Comment by MaxWinterstein** [comment]
@jooola any help is highly welcomed! I am not sure on how to achive this, but would love to!

**Comment by MaxWinterstein** [comment]
@jooola I used the coffee break to claim @shfmt-py - will continue to move / update asap.

**Comment by jooola** [comment]
@MaxWinterstein I think this project is not relevant anymore, at least for my needs.

I am using the following:
```yml
  - repo: local
    hooks:
      - id: shfmt
        name: shfmt
        description: Format shell scripts with shfmt
        language: golang
        additional_dependencies: [mvdan.cc/sh/v3/cmd/shfmt@v3.7.0]
        entry: shfmt -i 2 -ci -sr -kp -w
        types: [shell]
```
